version: "3.7"
services:
  web-site:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "8087:80"
    networks:
      - web
networks:
  web:
    external: true
